### ISSUE TITLE
Batch Operations in Boltdb

### ISSUE THREAD

**Issue by raunakj94** [skyec/boltdb-server#1]
There are various unique id and all are bidding a amount at a rate of milliseconds and I have to store it and update their current spend(the total sum of the bids till that time) asap. The schema i am using is like --a bucket for every unique id and storing the time as the key and value as the bid. --a common bucket for all unique and updating their current spend in that where key=unique id and value = latest current spend . As in this case which interface should I prefer. And how can I increase the rate of updating the value i.e.should i use db.Update() or db.Batch() and how ?

**Comment by skyec** [comment]
There are lots of things that could impact your performance and just as many ways to solve them. How durable do your writes need to be (to they need to be sync'ed)? Are you using spinning disks or SSD's? How consistent does your data model need to be (IOW do reads always need to see the latest writes)? I get close to 5000 writes per second to a single bucket using `Update()` on my MBP (SSD). That's less than 1/2 a millisecond per write. What are your write throughput requirements? Do you have code that you have benchmarked that isn't performing the way you need to?

Batching should speed things up though I don't have benchmarks to confirm. Each Update performs a sync for durability. If you batch then it only does a sync once for the whole batch update. However, if a batch fails, then _all_ updates made in that batch are rolled back. Is that acceptable for you? What's your failure mode? 

How durable do your writes need to be? If it is OK to return to the caller before ensuring the update is written to disk then simply queueing writes and performing writes in batches should be simple. If you need to ensure that the write is persisted to disk before returning you can consider a tx log (open/append) model with a single goroutine that updates the bolt db in the background. Both of these assume that you can have an amount of inconsistency between readers and writers.

**Comment by skyec** [comment]
You might also find following this thread informative: https://twitter.com/kellabyte/status/608667840544157696

And have you looked at the example code for `Batch`?
https://godoc.org/github.com/boltdb/bolt#DB.Batch

**Comment by raunakj94** [comment]
Thanks a lot for the explanation.
https://github.com/raunakspecial1994/GoCodes/blob/master/Boltdb-Aerospike/bolt.go

This is the simple code for a static data set that I have done for updating and reading data.I current_spend need to be updated as soon as we got a new bid.Bids are coming within milliseconds.
How can i improve this code? any suggestion will really be helpful.
